### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by LuisCGForte** [azerothcore/mod-transmog#58]
Hello
today I cloned the repository from azerothcore and this module
however when I try to compile on Ubuntu 20.04 I get the error
`/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:83: undefined reference to `Addmod_transmog_masterScripts()'`

![image](https://user-images.githubusercontent.com/20118021/143130226-4ce66072-715e-4250-9e76-27cc90f8f98b.png)

**Comment by LuisCGForte** [comment]
Fixed by changing module folder name "mod-transmog-master" to "mod-transmog"
make clean
